### ISSUE TITLE
Expat, tslib and libusb cannot be downloaded

### ISSUE THREAD

**Issue by theoriginalgri** [Illuminux/arm-cross-sysroot#1]
```
Build expat:
Download expat-2.1.0.tar.gz... 
######################################################################## 100,0%
Extract expat-2.1.0.tar.gz... faild
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

*** Error in expat ***
```

It seems sourceforge does not allow the direct links. I had to open the links in the browser and copy the files to the download directory used by your script.

**Comment by Illuminux** [comment]
The script does not use direct links for sourceforge, curl runs with the follow redirect option. 
But sometimes there is a timeout  and curl aborts. The archive is then corrupted and cannot be extracted. I haven't found a solution for the issue.
